//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_codec {
  vx_codec_pcmu = 0x1,
  vx_codec_siren7 = 0x2,
  vx_codec_siren14 = 0x4,
  vx_codec_opus8 = 0x10,
  vx_codec_opus40 = 0x20,
  vx_codec_opus57 = 0x40,
  vx_codec_opus72 = 0x80
}
