//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_participant_diagnostic_state_t {
  participant_diagnostic_state_speaking_while_mic_muted = 1,
  participant_diagnostic_state_speaking_while_mic_volume_zero = 2,
  participant_diagnostic_state_no_capture_device = 3,
  participant_diagnostic_state_no_render_device = 4,
  participant_diagnostic_state_capture_device_read_errors = 5,
  participant_diagnostic_state_render_device_write_errors = 6
}
