//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_tts_destination {
  tts_dest_remote_transmission = 0,
  tts_dest_local_playback = 1,
  tts_dest_remote_transmission_with_local_playback = 2,
  tts_dest_queued_remote_transmission = 3,
  tts_dest_queued_local_playback = 4,
  tts_dest_queued_remote_transmission_with_local_playback = 5,
  tts_dest_screen_reader = 6
}
