//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum vx_tts_status {
  tts_status_success = 0,
  tts_error_invalid_engine_type = -1001,
  tts_error_engine_allocation_failed = -1002,
  tts_error_not_supported = -1003,
  tts_error_max_characters_exceeded = -1004,
  tts_error_utterance_below_min_duration = -1005,
  tts_status_input_text_was_enqueued = -1006,
  tts_error_sdk_not_initialized = -1007,
  tts_error_destination_queue_is_full = -1008,
  tts_status_enqueue_not_necessary = -1009,
  tts_error_utterance_not_found = -1010,
  tts_error_manager_not_found = -1011,
  tts_error_invalid_argument = -1012,
  tts_error_internal = -1013
}
